title: Faisal Ahmad
logo: "/images/profile_pic.jpg"
description: >
  Full Stack Software Engineer
  <br>
  <a href="https://www.linkedin.com/in/faisal-ahmad-67216139/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
# google_analytics: UA-000000-0
